name: Multi Stage Deploy

on:
  push:
    branches:
      - main

env:
    AWS_REGION: ap-southeast-1

jobs:
  staging:
    name: Deploy to Staging
    environment:
      name: Staging
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Run Snyk to check Kubernetes manifest file for issues
        uses: snyk/actions/iac@master
        env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
            command: snyk iac test
            args: --servertity-threshold=high

      - name: Terraform Plan
        run: terraform plan

  production:
    name: Deploy to Production
    environment:
      name: Production
    runs-on: ubuntu-latest
    if: github.event.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Echo
        run: echo "Deploying to Production"
      