name: Multi Stage Deploy

on:
  push:
    branches:
      - main

env:
    # AWS_REGION: ap-southeast-1
    # ECS_CLUSTER: app_cluster
    # CONTAINER_NAME: app
    # ECS_SERVICE: app_service
    # # ECS_TD: .github/workflows/td.json

jobs:
  staging:
    name: Deploy to Staging
    environment:
      name: Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

  production:
    name: Deploy to Production
    environment:
      name: Production
    runs-on: ubuntu-latest
    if: github.event.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Echo
        run: echo "Deploying to Production"
      