name: Multi Stage Deploy

on:
  push:
    branches:
      - main

jobs:
  staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Staging
        run: |
          echo "Deploying to Staging"
          echo "Deployed to Staging"

  production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: |
          echo "Deploying to Production"
          echo "Deployed to Production"
