name: Multi Stage Deploy

on:
  push:
    branches:
      - main

jobs:
  staging:
    name: Deploy to Staging
    environment:
      name: Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Staging
        run: |
          echo "Deploying to Staging"
          echo "Deployed to Staging"

  production:
    if:  github.event.ref == 'refs/heads/main'
    name: Deploy to Production
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: |
          echo "Deploying to Production"
          echo "Deployed to Production"
